package com.example.yfr.list.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.yfr.list.db.Entity;

import com.example.yfr.list.db.EntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entityDaoConfig;

    private final EntityDao entityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entityDaoConfig = daoConfigMap.get(EntityDao.class).clone();
        entityDaoConfig.initIdentityScope(type);

        entityDao = new EntityDao(entityDaoConfig, this);

        registerDao(Entity.class, entityDao);
    }
    
    public void clear() {
        entityDaoConfig.clearIdentityScope();
    }

    public EntityDao getEntityDao() {
        return entityDao;
    }

}
