package com.example.yfr.list.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.yfr.list.db.UserEntity;
import com.example.yfr.list.db.Entity;

import com.example.yfr.list.db.UserEntityDao;
import com.example.yfr.list.db.EntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig entityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final EntityDao entityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        entityDaoConfig = daoConfigMap.get(EntityDao.class).clone();
        entityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        entityDao = new EntityDao(entityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(Entity.class, entityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.clearIdentityScope();
        entityDaoConfig.clearIdentityScope();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public EntityDao getEntityDao() {
        return entityDao;
    }

}
